"""update db 0.1

Revision ID: 34ee2197e16b
Revises: 
Create Date: 2024-05-18 06:45:25.289124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ee2197e16b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surah',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_surah', sa.Integer(), nullable=True),
    sa.Column('nama_surah', sa.String(length=15), nullable=True),
    sa.Column('id_ayat', sa.Integer(), nullable=True),
    sa.Column('text_ayat', sa.Text(), nullable=True),
    sa.Column('text_ayat_perkata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('surah', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_surah_nama_surah'), ['nama_surah'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surah', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_surah_nama_surah'))

    op.drop_table('surah')
    # ### end Alembic commands ###
