"""add history and message

Revision ID: 77e5daedefa0
Revises: 34ee2197e16b
Create Date: 2025-04-03 00:50:40.224666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e5daedefa0'
down_revision = '34ee2197e16b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_surah', sa.String(length=15), nullable=True),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_history_nama_surah'), ['nama_surah'], unique=False)
        batch_op.create_index(batch_op.f('ix_history_waktu'), ['waktu'], unique=False)

    op.create_table('pesan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dari', sa.Text(), nullable=True),
    sa.Column('isi', sa.Text(), nullable=True),
    sa.Column('waktu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('surah_fts_docsize')
    op.drop_table('surah_fts_content')
    op.drop_table('surah_fts_data')
    op.drop_table('surah_fts_config')
    op.drop_table('surah_fts')
    op.drop_table('surah_fts_idx')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surah_fts_idx',
    sa.Column('segid', sa.NullType(), nullable=False),
    sa.Column('term', sa.NullType(), nullable=False),
    sa.Column('pgno', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('segid', 'term')
    )
    op.create_table('surah_fts',
    sa.Column('id_surah', sa.NullType(), nullable=True),
    sa.Column('nama_surah', sa.NullType(), nullable=True),
    sa.Column('text_ayat', sa.NullType(), nullable=True),
    sa.Column('id_ayat', sa.NullType(), nullable=True)
    )
    op.create_table('surah_fts_config',
    sa.Column('k', sa.NullType(), nullable=False),
    sa.Column('v', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('surah_fts_data',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('block', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surah_fts_content',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('c0', sa.NullType(), nullable=True),
    sa.Column('c1', sa.NullType(), nullable=True),
    sa.Column('c2', sa.NullType(), nullable=True),
    sa.Column('c3', sa.NullType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surah_fts_docsize',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sz', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pesan')
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_history_waktu'))
        batch_op.drop_index(batch_op.f('ix_history_nama_surah'))

    op.drop_table('history')
    # ### end Alembic commands ###
